## Numpy N-dimensional Array

NumPy is a Python library that can be used for scientific and numerical applications and is the
tool to use for linear algebra operations.
* The main data structure in NumPy is the ndarray,which is a shorthand name for N-dimensional array.
* When working with NumPy, data in an ndarray is simply referred to as an array.
* It is a fixed-sized array in memory that contains data of the same type, such as integers or floating point values.
* The data type supported by an array can be accessed via the dtype attribute on the array.
* The dimensions of an array can be accessed via the shape attribute that returns a tuple describing the length of each dimension. 
* There are a host of other attributes. 
* A simple way to create an array from data or simple Python data structures like a list is to use the array()   function. 
* The example below creates a Python list of 3 floating point values, then creates an ndarray from the list and access the arrays’ shape and data type.

In [22]:
# importing Numpy

import numpy as np

# creating np array
a = np.array([1,2.3,25,0.1])

print(a)

#printing the shape of array

print('shape = ',a.shape)

#printing the Dtype of numpy

print(a.dtype)

[ 1.   2.3 25.   0.1]
shape =  (4,)
float64


In [23]:
# creating an empty array of shape 4*4

empty = np.empty([4,4])

print(empty)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
# creating a matrix of Zeros 

zeros = np.zeros([3,3])

print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# creating a matrix with ones

ones = np.ones([4,4])
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Combining Arrays

* NumPy provides many functions to create new arrays from existing arrays.

In [26]:
# Vertical Stack

v1 = np.array([9,7,0,0,5])

print(v1)
print(v1.shape)

print('\n')

v2 = np.array([0,6,0,2,2])
print(v2)
print(v2.shape)

print('\n')

vStack = np.vstack((v1,v2))
print(vStack)

[9 7 0 0 5]
(5,)


[0 6 0 2 2]
(5,)


[[9 7 0 0 5]
 [0 6 0 2 2]]


In [27]:
# horizontal Stack

h1 = np.array([[1,5],[4,5]])
print(h1)
print(h1.shape)
print('\n')


h2 = np.array([[2,8],[8,9]])
print(h2)
print(h2.shape)
print('\n')


hStack = np.hstack((h1,h2))
print(hStack)
print(h2.shape)

[[1 5]
 [4 5]]
(2, 2)


[[2 8]
 [8 9]]
(2, 2)


[[1 5 2 8]
 [4 5 8 9]]
(2, 2)


In [28]:
# convering list to array

list = [1,12,4,5,7]

ary = np.array(list)

print(type(ary))

<class 'numpy.ndarray'>


In [29]:
## Two-Dimensional List of Lists to Array

data = [[11, 22],
[33, 44],
[55, 66]]

arry = np.array(data)

print(arry)
print(arry.shape)
print(type(arry))

[[11 22]
 [33 44]
 [55 66]]
(3, 2)
<class 'numpy.ndarray'>


## Array Indexing 

In [30]:
# One_Dimensional Indexing

one_d = np.array([2,3,56,1,9,5])

print(one_d[2])
print(one_d[-1])
print(one_d[-6])

56
5
2


In [31]:
# Two-Dimensional Indexing

two_d = np.array([[1,5],
                  [459,52],
                 [443,65]])
print(two_d[0,0])

print(two_d[1,0])

print(two_d[2,1])

# for printing all the elements in a row

print(two_d[0,])

1
459
65
[1 5]


## Array Slicing

In [32]:
# One-Dimensional slicing 

one_Sl = np.array([6,7,4,9,3])

#to print all the  elements

print(one_Sl[:])

#The first item of the array can be sliced by specifying a slice that starts at index 0 and ends at index 1 

print(one_Sl[0:1])

print(one_Sl[1:4])

print(one_Sl[3:5])

# negative Slicing Can Also be Done

print(one_Sl[-2:])

print(one_Sl[-3:-1])

[6 7 4 9 3]
[6]
[7 4 9]
[9 3]
[9 3]
[4 9]


## Two-Dimensional Slicing

In [33]:
Two_sl = np.array([[1,2,3,4],
                  [3,6,7,3],
                  [9,5,2,8]])
x = Two_sl[:,:-1]
y = Two_sl[:,-1]

print(x)
print('\n')
print(y)

[[1 2 3]
 [3 6 7]
 [9 5 2]]


[4 3 8]


In [34]:
# Splitting the Data into Training Data and Test data

split = 2

train_x = x[:split,:]
test_x = x[split:,:]

print(train_x)
print('\n')
print(test_x)

[[1 2 3]
 [3 6 7]]


[[9 5 2]]


## Array Reshaping

In [38]:
# array 

Shape =np.array([[1,2,3,4],
        [5,6,8,9]])

print('Rows: %d' % Shape.shape[0])
print('Cols : %d' % Shape.shape[1])

Rows: 2
Cols : 4


In [45]:
# Reshape 1D to 2D Array

one_re = np.array([2,3,5,4,1])

print(one_re)
print(one_re.shape)

print('\n')
one_re = one_re.reshape(one_re.shape[0],1)

print(one_re)
print(one_re.shape)

[2 3 5 4 1]
(5,)


[[2]
 [3]
 [5]
 [4]
 [1]]
(5, 1)


In [53]:
# Reshape 2D to 3D Array

data = np.array([[11, 22],
[33, 44],
[55, 66]])

print(data)
print(data.shape)
print('\n')

data_3d = data.reshape(data.shape[0],data.shape[1],1)
print(data_3d)
print(data_3d.shape)

[[11 22]
 [33 44]
 [55 66]]
(3, 2)


[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
(3, 2, 1)


## NumPy Array Broadcasting

* Arrays with different sizes cannot be added, subtracted, or generally be used in arithmetic.
* A way to overcome this is to duplicate the smaller array so that it has the dimensionality and size as the larger array. 
* This is called array broadcasting and is available in NumPy when performing array arithmetic, which can greatly reduce and simplify your code.


In [57]:
## broadcast scalar to one-dimensional array

m = np.array([1,2,3,4])
n = np.array([5])
o = np.add(m,n)
print(o)

[6 7 8 9]


In [59]:
## broadcast scalar to Two-dimensional array

m = np.array([[1,2,4],[3,6,7]])
n = np.array([3])
o = np.add(m,n)
print(o)

[[ 4  5  7]
 [ 6  9 10]]


In [61]:

## broadcast oneD to twoD array

m = np.array([[1,2,3,4],[4,5,8,6]])
n = np.array([10,2,5,4])
o = np.add(m,n)
print(o)

[[11  4  8  8]
 [14  7 13 10]]
