## Vectors


In [1]:
# dedining the vector

import numpy as np
vec = np.array([1,5,6,8])
print(vec)

[1 5 6 8]


In [2]:
# arthemetic operations between two vectors to form third vector

vec1 = np.array([1,3,5,67,7])
vec2 = np.array([4,8,23,8,7])

In [3]:
# addition of two vectors

add = vec1 + vec2
print(add)
print('\n')
#or using numpy built_in_func 
add = np.add(vec1,vec2)
print(add)

[ 5 11 28 75 14]


[ 5 11 28 75 14]


In [4]:
# subtaction of two vectors

sub = vec1-vec2
print(sub)

print('\n')

#or using np  func

sub = np.subtract(vec1,vec2)
print(sub)

[ -3  -5 -18  59   0]


[ -3  -5 -18  59   0]


In [5]:
# multiplication of two vectors

mul = vec1 * vec2
print(mul)
print('\n')

#or using numpy func

mul = np.multiply(vec1,vec2)
print(mul)

[  4  24 115 536  49]


[  4  24 115 536  49]


In [6]:
#division of two vectors

div = vec1/vec2
print(div)
print('\n')

# or using numpy func


div  = np.divide(vec1,vec2)
print(div)

[0.25      0.375     0.2173913 8.375     1.       ]


[0.25      0.375     0.2173913 8.375     1.       ]


In [7]:
# dot-product of the two vectors

dot = vec1.dot(vec2)
print(dot)
print('\n')

# using np function

dot = np.dot(vec1,vec2)
print(dot)

728


728


In [8]:
# scalar to vector multiplication

scalar = 0.5

s_mul = np.multiply(vec1,scalar)
print(s_mul)

[ 0.5  1.5  2.5 33.5  3.5]


## Vector Norms

* Calculating the length or magnitude of vectors is often required either directly as a regularization method in machine learning, or as part of broader vector or matrix operations. 
* We will discover the different ways to calculate vector lengths or magnitudes, called the vector norm

* The L 1 norm that is calculated as the sum of the absolute values of the vector.
* The L 2 norm that is calculated as the square root of the sum of the squared vector values.
* The max norm that is calculated as the maximum vector values.

Vector L 1 Norm
* The length of a vector can be calculated using the L 1 norm, where the 1 is a superscript of the L. 
* The notation for the L 1 norm of a vector is ||v|| 1 , where 1 is a subscript. 
* As such, this length is sometimes called the taxicab norm or the Manhattan norm.

L 1 (v) = ||v|| 1

* The L 1 norm is calculated as the sum of the absolute vector values, where the absolute value of a scalar uses the notation |a 1 |.
* In effect, the norm is a calculation of the Manhattan distance from the origin of the vector space.

||v|| 1 = |a 1 | + |a 2 | + |a 3 |


* In several machine learning applications, it is important to discriminate betweenelements that are exactly zero and elements that are small but nonzero.
* In these cases, we turn to a function that grows at the same rate in all locations, but retains mathematical simplicity :   the L 1 norm.



In [9]:
# creating a L1 regularization using numpy

l1 = np.linalg.norm(vec1,1)
l1

83.0

* The length of a vector can be calculated using the L 2 norm, where the 2 is a superscript of the L. 
* The notation for the L 2 norm of a vector is ||v|| 2 where 2 is a subscript.


L 2 (v) = ||v|| 2


* The L 2 norm calculates the distance of the vector coordinate from the origin of the vector space.
* As such, it is also known as the Euclidean norm as it is calculated as the Euclidean distance from the origin.
* The result is a positive distance value.
* The L 2 norm is calculated as the square root of the sum of the squared vector values.


||v|| 2 = a 21 + a 22 + a 23




In [10]:
## crating a L2 regularization using np

l2 = np.linalg.norm(vec1)
l2

67.62396025078685

* The length of a vector can be calculated using the maximum norm, also called max norm.
* Max norm of a vector is referred to as L inf where inf is a superscript and can be represented with the infinity symbol.
* The notation for max norm is ||v|| inf , where inf is a subscript. L


inf (v) = ||v|| inf

* The max norm is calculated as returning the maximum value of the vector, hence the name.


||v|| inf = max a 1 , a 2 , a 3

In [11]:
from math import inf

max_norm = np.linalg.norm(vec,inf)

max_norm

8.0

# Matrices and Matrix Arithmetic

In [12]:
# defining a matrix

mat = np.array([[2,5],
                [6,8]])


print(mat)

[[2 5]
 [6 8]]


In [13]:
# addaing of two matrices

mat1 = np.array([[1,9],[7,9]])
mat2 = np.array([[2,6],[8,90]])


add = mat1 + mat2

print(add)
print('\n')

#or with np func

add = np.add(mat1,mat2)

print(add)

[[ 3 15]
 [15 99]]


[[ 3 15]
 [15 99]]


In [14]:
# subtarcting two matrices

sub = mat1 -mat2
print(sub)
print('\n')

#or with np func
sub = np.subtract(mat1,mat2)
print(sub)

[[ -1   3]
 [ -1 -81]]


[[ -1   3]
 [ -1 -81]]


In [15]:
# multipling two matrices 

mul = mat1 * mat2
print(mul)

print('\n')
# or with the mul func

mul = np.multiply(mat1,mat2)
print(mul)

[[  2  54]
 [ 56 810]]


[[  2  54]
 [ 56 810]]


In [16]:
# dividing two matrices

div = mat1/mat2
print(div)
print('\n')

#or with np func

div = np.divide(mat1,mat2)
print(div)

[[0.5   1.5  ]
 [0.875 0.1  ]]


[[0.5   1.5  ]
 [0.875 0.1  ]]


## Matrix-Matrix Multiplication

* Matrix multiplication, also called the matrix dot product is more complicated than the previous operations and involves a rule as not all matrices can be multiplied together.

* C = A · B (9.15)
* C = AB (9.16)

### or

* The rule for matrix multiplication is as follows:

* The number of columns (n) in the first matrix (A) must equal the number of rows (m) in the second matrix (B).
* For example, matrix A has the dimensions m rows and n columns and matrix B has the dimensions n and k.
* The n columns in A and n rows in B are equal.
* The result is a new matrix with m rows and k columns.

#### C(m, k) = A(m, n) · B(n, k)


* This rule applies for a chain of matrix multiplications where the number of columns in one matrix in the chain must match the number of rows in the following matrix in the chain.
* One of the most important operations involving matrices is multiplication of two matrices.
* The matrix product of matrices A and B is a third matrix C.
* In order for this product to be defined, A must have the same number of columns as B has rows.
* If A is of shape m × n and B is of shape n × p, then C is of shape m × p.



In [17]:
## mutrix matrix multiplication 

matmul1 = np.array([[[[1,3,6,8],
             [2,5,7,9],
             [8,2,0,1]]]])
matmul2 = np.array([[[[5,6,4,8,5],
              [6,5,2,4,6],
             [6,2,5,23,5],
                     [5,6,4,7,8]]]])



matmul = matmul1 @ matmul2
print(matmul)

print('\n')

#using numpy

matmul = np.matmul(matmul1,matmul2)

print(matmul)

[[[[ 99  81  72 214 117]
   [127 105  89 260 147]
   [ 57  64  40  79  60]]]]


[[[[ 99  81  72 214 117]
   [127 105  89 260 147]
   [ 57  64  40  79  60]]]]


In [18]:
## matrix with vaector mul
vec3 = np.array([1,2,3,4])

vec_matmul =matmul1 @ vec3

vec_matmul

array([[[57, 69, 16]]])

In [19]:
## scalar to matrix multiplication 

sc = 34

sc_matmul = matmul2 * sc

print(sc_matmul)

print('\n')
#or in numpy built in func

sc_mul = np.multiply (matmul2,sc)
print(sc_matmul)

[[[[170 204 136 272 170]
   [204 170  68 136 204]
   [204  68 170 782 170]
   [170 204 136 238 272]]]]


[[[[170 204 136 272 170]
   [204 170  68 136 204]
   [204  68 170 782 170]
   [170 204 136 238 272]]]]


# Types of Matrices

In [20]:
# Triangular matrix

lower = np.tril(sc_mul)
print(lower)

print('\n')
upper = np.triu(sc_mul)
print(upper)

[[[[170   0   0   0   0]
   [204 170   0   0   0]
   [204  68 170   0   0]
   [170 204 136 238   0]]]]


[[[[170 204 136 272 170]
   [  0 170  68 136 204]
   [  0   0 170 782 170]
   [  0   0   0 238 272]]]]


In [21]:
# Diagonal matrix

matmul2 = np.array([[6,4,8],
              [6,5,2],
             [6,2,5]])

diag = np.diag(matmul2)
print(diag)

[6 5 5]


In [22]:
#Identity matrix

identity = np.identity(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
# orthogonal matrix
from numpy import array
from numpy.linalg import inv
# define orthogonal matrix
Q = array([
[1, 0],
[0, -1]])
print(Q)
# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)
# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


# Operations of matrices

##  1 Transpose

* A defined matrix can be transposed, which creates a new matrix with the number of columns and rows flipped. 
* This is denoted by the superscript T next to the matrix A T .


### C = A T

* We can transpose a matrix in NumPy by calling the T attribute.

In [24]:
# transpose matrix
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# calculate transpose
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


## Inverse

In [25]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## Trace

In [26]:
A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

print('\n')
trace = np.trace(A)
print(trace)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


15


## Determinant

In [27]:
b = np.linalg.det(A)
print(b)

-9.51619735392994e-16


## Rank

In [28]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [29]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
[0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)
# rank 1
M1 = array([
[1,2],
[1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)
# rank 2
M2 = array([
[1,2],
[3,4]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2


In [30]:
# sparsity calculation
from numpy import array
from numpy import count_nonzero
# create dense matrix
A = array([
[1, 0, 0, 1, 0, 0],
[0, 0, 2, 0, 0, 1],
[0, 0, 0, 2, 0, 0]])
print(A)
# calculate sparsity
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
0.7222222222222222


## Tensors

In [39]:
tensors = np.array([[[1,2,3],[1,3,4],[5,6,7]],
                    [[8,5,4],[1,3,5],[9,4,3]],
                    [[1,6,3],[55,77,33],[4,9,4]]])
print(tensors)
print(tensors.shape)
print(np.linalg.matrix_rank(tensors))

[[[ 1  2  3]
  [ 1  3  4]
  [ 5  6  7]]

 [[ 8  5  4]
  [ 1  3  5]
  [ 9  4  3]]

 [[ 1  6  3]
  [55 77 33]
  [ 4  9  4]]]
(3, 3, 3)
[3 3 3]


In [42]:
# tensor addition
import numpy as np
# define first tensor
A =np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# add tensors
C = A + B
print(C)
print('\n')

# using np add func()
c = np.add(A,B)
print(c)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [52]:
# tensor subtraction

c = A - B
print(c)
print('\n')

# by builtin func 

c = np.subtract(A,B)
print(c)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [54]:
# tensor Hadamard Product

c = A * B
print(c)

print('\n')

c = np.multiply(A,B)
print(c)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


In [51]:
# tensor division


c = A / B
print(c)

# by built in func 
print('\n')
c = np.divide(A,B)
print(c)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [60]:
#Tensor Product

c = np.tensordot(A,B,axes=0)

print(np.linalg.matrix_rank(c))

print('\n')

print(c.shape)

[[[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]]


(3, 3, 3, 3, 3, 3)
